### ISSUE TITLE
Setup CD

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/doc-snippets#1]
Setup CD for this repo, such that new pushes into master can trigger a release. You could reference how this is done in some of our other repos, like for example the toolchain repo where we:
- have a list of PUBLISHERS defined in a file that's checked-in
- have a special naming convention for PRs to trigger new releases (PR title ends in `/workflows/release-pr`)
- releases are publishes to GitHub & NPM

**Comment by pileks** [comment]
Should be considered resolved with successful publish associated with #8
